pipeline {
  agent {
    kubernetes {
      	cloud 'kubernetes'
      	defaultContainer 'jnlp'
      }
    }
  stages {
    stage('Deploy App') {
      steps {
        script {
          kubernetesDeploy(configs: "/testing/hello-docker.yml", kubeconfigId: "kubeconfig")
        }
      }
    }
  }
}
